sudo: required
services:
  - docker

before_install:
  - docker build -t yoryer/docker-react-test -f Dockerfile.dev .

script:
  - docker run yoryer/docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-sa-east-1-830618992450"
  bucket_path: docker-react-test"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"